Add option to submit blocks only with bundles
flashbots/builder pull request #16
Opened 2022-12-03 01:37 UTC by adrianchifor

Adding an extra option on builder so we can skip submitting blocks to relays if they don't include any bundles. Mempool-only blocks with naive algos like greedy or mev-geth are not competitive enough to get bought in the majority of cases, and they can become spammy on relays if more people start running builders.

```
--builder.only_bundle_blocks   (default: false)
        Submit only blocks with bundles
```

```
INFO [...] Block finalized and assembled ...
INFO [...] No bundles included, skipping block submission  slot=...
```

2022-12-03 09:53 UTC, Ruteri commented
If the flag were on the miner config, you could avoid all the computation as you already know you can't build a block as soon as `txpool.MevBundles` call. I think it's worth it, as we anyway have builder-specific miner flags. what do you think?

2022-12-03 11:00 UTC, adrianchifor commented
> If the flag were on the miner config, you could avoid all the computation as you already know you can't build a block as soon as `txpool.MevBundles` call. I think it's worth it, as we anyway have builder-specific miner flags. what do you think?

Nice good point, updated to miner.

2022-12-06 10:22 UTC, Ruteri requested changes
Make sure to cover all places where `MevBundles` is called (one more fillTransactionsAlgoWorker or something).

2022-12-06 10:22 UTC, Ruteri commented on cmd/utils/flags.go
> +	cfg.OnlyBlocksWithBundles = ctx.IsSet(MinerOnlyBlocksWithBundlesFlag.Name)
Won't this also be the case for `--miner.only_bundle_blocks=false`?

2023-01-13 12:16 UTC, closed without merging